export interface DataType {
    aspek_penilaian_1: {
        mahasiswa_1: number,
        mahasiswa_2: number,
        mahasiswa_3: number,
        mahasiswa_4: number,
        mahasiswa_5: number,
        mahasiswa_6: number,
        mahasiswa_7: number,
        mahasiswa_8: number,
        mahasiswa_9: number,
        mahasiswa_10: number,
    },
    aspek_penilaian_2: {
        mahasiswa_1: number,
        mahasiswa_2: number,
        mahasiswa_3: number,
        mahasiswa_4: number,
        mahasiswa_5: number,
        mahasiswa_6: number,
        mahasiswa_7: number,
        mahasiswa_8: number,
        mahasiswa_9: number,
        mahasiswa_10: number,
    },
    aspek_penilaian_3: {
        mahasiswa_1: number,
        mahasiswa_2: number,
        mahasiswa_3: number,
        mahasiswa_4: number,
        mahasiswa_5: number,
        mahasiswa_6: number,
        mahasiswa_7: number,
        mahasiswa_8: number,
        mahasiswa_9: number,
        mahasiswa_10: number,
    },
    aspek_penilaian_4: {
        mahasiswa_1: number,
        mahasiswa_2: number,
        mahasiswa_3: number,
        mahasiswa_4: number,
        mahasiswa_5: number,
        mahasiswa_6: number,
        mahasiswa_7: number,
        mahasiswa_8: number,
        mahasiswa_9: number,
        mahasiswa_10: number,
    },
}